"""
Django settings for BillingSystem project.

Generated by 'django-admin startproject' using Django 3.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

from pathlib import Path
import os
from django.shortcuts import render
from django.shortcuts import redirect,HttpResponseRedirect
from myApp import BillingDB
from myApp import GeneratePenalty
DB_CREDINTIALS = BillingDB.DB_CREDINTIALS()
Secret_STR = BillingDB.Secret_Secret
ReqParams = BillingDB.ReqParams()



# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'bdji1+*1d!*l3s0r5l2^&r$)nb1%*1*gj1pe@n94d8^fhdumsz'
#'bdji1+*1d!*l3s0r5l2^&r$)nb1%*1*gj1pe@n94d8^fhdumsz'
#'bdji1+*1d!*l3s0r5l2^&r$)nb1%*1*gj1pe@n94d8^fhdumsz'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
#'192.168.43.68'
ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    #'dbbackup',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    #'rest_framework',
    'myApp',
    #'django_crontab',
    'chartjs',
    'django_apscheduler',

    
]
#DBBACKUP_STORAGE = 'django.core.files.storage.FileSystemStorage'
#DBBACKUP_STORAGE_OPTIONS = {'location':   BASE_DIR / 'backupdb'}




MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'BillingSystem.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR,'templates/html')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'BillingSystem.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE':  DB_CREDINTIALS.ENGINE,
        'NAME': DB_CREDINTIALS.NAME,
        'USER': DB_CREDINTIALS.USER,
        'PASSWORD': DB_CREDINTIALS.PASSWORD,
        'HOST' : DB_CREDINTIALS.HOST,
        'PORT': DB_CREDINTIALS.PORT,

         'OPTIONS': {
         "init_command": "SET foreign_key_checks = 0;",
    },
        
    }
}



# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

STATIC_URL = '/static/'

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
    ]
    
EMAIL_BACKEND = ReqParams.EMAIL_BACKEND
EMAIL_HOST = ReqParams.EMAIL_HOST
EMAIL_USE_TLS = ReqParams.EMAIL_USE_TLS
EMAIL_PORT = ReqParams.EMAIL_PORT
EMAIL_HOST_USER = ReqParams.EMAIL_HOST_USER
EMAIL_HOST_PASSWORD = ReqParams.EMAIL_HOST_PASSWORD
ACCOUNT_EMAIL_VERIFICATION = 'none'
EMAIL_USE_TLS = True

SESSION_EXPIRE_AT_BROWSER_CLOSE = True
MESSAGE_LEVEL = 10

