# Generated by Django 3.1.3 on 2021-03-21 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usage_record',
            name='consumerid',
        ),
    ]
