# Generated by Django 3.1.3 on 2021-03-21 06:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_remove_usage_record_consumerid'),
    ]

    operations = [
        migrations.AddField(
            model_name='usage_record',
            name='consumerid',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='myApp.consumers_info'),
        ),
    ]
