# Generated by Django 3.1.3 on 2021-03-21 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0003_usage_record_consumerid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revenuecode',
            name='additionalfee_pipe_of_20_lineal_feet',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='revenuecode',
            name='application_fee',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='revenuecode',
            name='asphalted_road',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='revenuecode',
            name='cemented_road',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='revenuecode',
            name='commercialservice_excess_per_cubicmeter',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='revenuecode',
            name='commercialservice_per_month',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='revenuecode',
            name='drilling_from_mainline',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='revenuecode',
            name='gravel_excavation',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='revenuecode',
            name='mayors_permit',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='revenuecode',
            name='reinstallation_fee',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='revenuecode',
            name='repair_fee',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='revenuecode',
            name='residentialservice_excess_per_cubicmeter',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='revenuecode',
            name='residentialservice_per_month',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='revenuecode',
            name='tapping_fee',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='revenuecode',
            name='three_month_penalty',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='revenuecode',
            name='transfer_fee',
            field=models.FloatField(default=0),
        ),
    ]
