# Generated by Django 3.1.3 on 2021-04-08 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0004_auto_20210321_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicants_info',
            name='address_installation',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='applicants_info',
            name='checker_comment',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='applicants_info',
            name='engineer_comment',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='applicants_info',
            name='mayor_comment',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='applicants_info',
            name='required_files',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='applicants_info',
            name='required_image',
            field=models.CharField(max_length=100),
        ),
    ]
