# Generated by Django 3.1.3 on 2021-04-08 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0005_auto_20210408_2338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicants_info',
            name='checker_comment',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='applicants_info',
            name='engineer_comment',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='applicants_info',
            name='mayor_comment',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='applicants_info',
            name='required_files',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='applicants_info',
            name='required_image',
            field=models.CharField(max_length=300),
        ),
    ]
