# Generated by Django 3.1.3 on 2021-04-09 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0006_auto_20210408_2340'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicants_info',
            name='consimerid',
            field=models.CharField(default='', max_length=30),
        ),
    ]
