# Generated by Django 3.1.3 on 2021-04-10 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0007_applicants_info_consimerid'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicants_info',
            name='date_checkercommented',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='applicants_info',
            name='date_engineercommented',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='applicants_info',
            name='date_mayorcommented',
            field=models.CharField(default='', max_length=30),
        ),
    ]
