# Generated by Django 3.1.3 on 2021-04-10 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0008_auto_20210410_1447'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applicants_info',
            old_name='consimerid',
            new_name='consumerid',
        ),
        migrations.AlterField(
            model_name='applicants_info',
            name='date_checkercommented',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='applicants_info',
            name='date_engineercommented',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='applicants_info',
            name='date_mayorcommented',
            field=models.CharField(default='', max_length=500),
        ),
    ]
