# Generated by Django 3.1.3 on 2021-04-11 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0009_auto_20210410_1524'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicants_info',
            name='required_image',
        ),
    ]
