# Generated by Django 3.1.3 on 2021-04-11 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0011_applicants_info_required_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicants_info',
            name='profilepic',
            field=models.FileField(default='ui-admin.jpg', upload_to=''),
        ),
    ]
