# Generated by Django 3.1.3 on 2021-04-11 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0012_auto_20210411_2317'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicants_info',
            name='required_image',
        ),
    ]
