# Generated by Django 3.1.3 on 2021-04-11 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0013_remove_applicants_info_required_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicants_info',
            name='required_image',
            field=models.CharField(default='', max_length=300),
        ),
    ]
