# Generated by Django 3.1.3 on 2021-04-12 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0014_applicants_info_required_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicants_info',
            name='profilepic',
            field=models.CharField(default='ui-admin.jpg|', max_length=100),
        ),
    ]
