# Generated by Django 3.1.3 on 2021-04-12 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0016_auto_20210412_2241'),
    ]

    operations = [
        migrations.CreateModel(
            name='System_Host',
            fields=[
                ('id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('emailhost', models.EmailField(max_length=254)),
                ('first_approver_email', models.EmailField(max_length=254)),
                ('second_approver_email', models.EmailField(max_length=254)),
                ('final_approver_email', models.EmailField(max_length=254)),
                ('teller_email', models.EmailField(default='', max_length=254)),
                ('supervisor_email', models.EmailField(default='', max_length=254)),
                ('phonenumber_host', models.CharField(default='', max_length=30)),
            ],
            options={
                'db_table': 'systemhost',
            },
        ),
    ]
