# Generated by Django 3.1.3 on 2021-04-13 07:42

from django.db import migrations,models



class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0017_system_host'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumers_info',
            name='mobilenumber',
            field=models.CharField(max_length=128 ),
        ),
        migrations.AlterField(
            model_name='consumers_info',
            name='mobilenumber2',
            field=models.CharField(max_length=128 ),
        ),
    ]
