# Generated by Django 3.1.3 on 2021-04-13 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0018_auto_20210413_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='year_report',
            name='amountpaid_str',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='usage_record',
            name='datepaid_apr',
            field=models.CharField(default=' ', max_length=300),
        ),
        migrations.AlterField(
            model_name='usage_record',
            name='datepaid_aug',
            field=models.CharField(default=' ', max_length=300),
        ),
        migrations.AlterField(
            model_name='usage_record',
            name='datepaid_dec',
            field=models.CharField(default=' ', max_length=300),
        ),
        migrations.AlterField(
            model_name='usage_record',
            name='datepaid_feb',
            field=models.CharField(default=' ', max_length=300),
        ),
        migrations.AlterField(
            model_name='usage_record',
            name='datepaid_jan',
            field=models.CharField(default=' ', max_length=300),
        ),
        migrations.AlterField(
            model_name='usage_record',
            name='datepaid_jul',
            field=models.CharField(default=' ', max_length=300),
        ),
        migrations.AlterField(
            model_name='usage_record',
            name='datepaid_jun',
            field=models.CharField(default=' ', max_length=300),
        ),
        migrations.AlterField(
            model_name='usage_record',
            name='datepaid_may',
            field=models.CharField(default=' ', max_length=300),
        ),
        migrations.AlterField(
            model_name='usage_record',
            name='datepaid_nov',
            field=models.CharField(default=' ', max_length=300),
        ),
        migrations.AlterField(
            model_name='usage_record',
            name='datepaid_oct',
            field=models.CharField(default=' ', max_length=300),
        ),
        migrations.AlterField(
            model_name='usage_record',
            name='datepaid_sept',
            field=models.CharField(default=' ', max_length=300),
        ),
        migrations.AlterField(
            model_name='usage_record',
            name='dateposted_mar',
            field=models.CharField(default=' ', max_length=300),
        ),
    ]
