# Generated by Django 3.1.3 on 2021-04-13 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0019_auto_20210413_2204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='year_report',
            name='amountpaid_str',
        ),
        migrations.AddField(
            model_name='usage_record',
            name='amountpaid_str',
            field=models.CharField(default='', max_length=300),
        ),
    ]
