# Generated by Django 3.1.3 on 2021-04-13 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0020_auto_20210413_2205'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usage_record',
            old_name='amountpaid_str',
            new_name='amountpaid_str_apr',
        ),
        migrations.AddField(
            model_name='usage_record',
            name='amountpaid_str_aug',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='usage_record',
            name='amountpaid_str_dec',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='usage_record',
            name='amountpaid_str_feb',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='usage_record',
            name='amountpaid_str_jan',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='usage_record',
            name='amountpaid_str_jul',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='usage_record',
            name='amountpaid_str_jun',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='usage_record',
            name='amountpaid_str_mar',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='usage_record',
            name='amountpaid_str_may',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='usage_record',
            name='amountpaid_str_nov',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='usage_record',
            name='amountpaid_str_oct',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='usage_record',
            name='amountpaid_str_sept',
            field=models.CharField(default='', max_length=300),
        ),
    ]
