# Generated by Django 3.1.3 on 2021-04-15 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0021_auto_20210413_2211'),
    ]

    operations = [
        migrations.CreateModel(
            name='Primarykey_Basis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classification', models.CharField(max_length=30)),
                ('lastid_used', models.IntegerField()),
            ],
            options={
                'db_table': 'primarykey_basis',
            },
        ),
        migrations.DeleteModel(
            name='System_Host',
        ),
        migrations.AddField(
            model_name='consumers_info',
            name='oldconsumerid',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='consumers_info',
            name='mobilenumber',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='consumers_info',
            name='mobilenumber2',
            field=models.CharField(max_length=30),
        ),
    ]
