# Generated by Django 3.1.3 on 2021-04-15 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0022_auto_20210415_1950'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='primarykey_basis',
            name='id',
        ),
        migrations.AlterField(
            model_name='primarykey_basis',
            name='classification',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
    ]
