# Generated by Django 3.1.3 on 2021-04-17 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0023_auto_20210415_1957'),
    ]

    operations = [
        migrations.AddField(
            model_name='usage_record',
            name='accountinfoid',
            field=models.CharField(default='', max_length=30),
        ),
    ]
