# Generated by Django 3.1.3 on 2021-05-12 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0026_auto_20210430_2156'),
    ]

    operations = [
        migrations.AddField(
            model_name='usage_record',
            name='penalty_flag',
            field=models.CharField(default='', max_length=30),
        ),
    ]
