# Generated by Django 3.1.3 on 2021-05-13 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0027_usage_record_penalty_flag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usage_record',
            name='penalty_flag',
            field=models.IntegerField(default=0),
        ),
    ]
