# Generated by Django 3.1.3 on 2021-05-13 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0028_auto_20210514_0003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usage_record',
            name='penalty_flag',
        ),
    ]
