# Generated by Django 3.2 on 2021-07-06 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0030_usage_record_penalty_flag'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeterReadingModification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accountinfoid', models.CharField(default='', max_length=30)),
                ('reading', models.FloatField()),
                ('month', models.IntegerField()),
                ('date', models.CharField(max_length=30)),
                ('meternumber', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=30)),
                ('postedby', models.CharField(default='', max_length=30)),
            ],
            options={
                'db_table': 'meterreadingmodification_table',
            },
        ),
    ]
