# Generated by Django 3.1.3 on 2021-07-05 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0031_meterreadingmodification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meterreadingmodification',
            name='month',
            field=models.CharField(max_length=30),
        ),
    ]
