# Generated by Django 3.1.3 on 2021-07-05 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0032_auto_20210705_0930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meterreadingmodification',
            name='reading',
            field=models.FloatField(default=0),
        ),
    ]
