# Generated by Django 3.1.3 on 2021-07-05 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0033_auto_20210705_0931'),
    ]

    operations = [
        migrations.AddField(
            model_name='meterreadingmodification',
            name='meternumber',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='meterreadingmodification',
            name='name',
            field=models.CharField(default='', max_length=30),
        ),
    ]
