# Generated by Django 3.1.3 on 2021-07-05 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0034_auto_20210705_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meterreadingmodification',
            name='month',
            field=models.IntegerField(default=0),
        ),
    ]
