# Generated by Django 3.1.3 on 2021-07-05 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0035_auto_20210705_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meterreadingmodification',
            name='meternumber',
            field=models.CharField(default=0, max_length=30),
        ),
    ]
