# Generated by Django 3.1.3 on 2021-07-05 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0036_auto_20210705_1407'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meterreadingmodification',
            name='accountinfoid',
        ),
        migrations.AlterField(
            model_name='meterreadingmodification',
            name='meternumber',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='meterreadingmodification',
            name='month',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='meterreadingmodification',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='meterreadingmodification',
            name='reading',
            field=models.FloatField(),
        ),
    ]
