# Generated by Django 3.1.3 on 2021-07-05 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0037_auto_20210705_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='meterreadingmodification',
            name='accountinfoid',
            field=models.CharField(default='', max_length=30),
        ),
    ]
