# Generated by Django 3.1.3 on 2021-07-06 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0039_meterreadingmodification_postedby'),
    ]

    operations = [
        migrations.AddField(
            model_name='gettotalbill',
            name='previous_reading',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='gettotalbill',
            name='reading_date',
            field=models.CharField(default='', max_length=30),
        ),
    ]
