# Generated by Django 3.1.3 on 2021-07-08 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0042_auto_20210707_0942'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meterreadingmodification',
            name='id',
        ),
        migrations.AlterField(
            model_name='meterreadingmodification',
            name='accountinfoid',
            field=models.CharField(default='', max_length=30, primary_key=True, serialize=False),
        ),
    ]
