# Generated by Django 3.1.3 on 2021-07-12 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0043_auto_20210708_0814'),
    ]

    operations = [
        migrations.AddField(
            model_name='gettotalbill',
            name='consumption',
            field=models.FloatField(default=0),
        ),
    ]
