# Generated by Django 3.1.3 on 2021-07-12 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0044_gettotalbill_consumption'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gettotalbill',
            old_name='id',
            new_name='bill_id',
        ),
    ]
