# Generated by Django 3.1.3 on 2021-07-14 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0045_auto_20210712_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usage_record',
            name='postedby_apr',
            field=models.CharField(default=' ', max_length=300),
        ),
        migrations.AlterField(
            model_name='usage_record',
            name='postedby_aug',
            field=models.CharField(default=' ', max_length=300),
        ),
        migrations.AlterField(
            model_name='usage_record',
            name='postedby_dec',
            field=models.CharField(default=' ', max_length=300),
        ),
        migrations.AlterField(
            model_name='usage_record',
            name='postedby_feb',
            field=models.CharField(default=' ', max_length=300),
        ),
        migrations.AlterField(
            model_name='usage_record',
            name='postedby_jan',
            field=models.CharField(default=' ', max_length=300),
        ),
        migrations.AlterField(
            model_name='usage_record',
            name='postedby_jul',
            field=models.CharField(default=' ', max_length=300),
        ),
        migrations.AlterField(
            model_name='usage_record',
            name='postedby_jun',
            field=models.CharField(default=' ', max_length=300),
        ),
        migrations.AlterField(
            model_name='usage_record',
            name='postedby_mar',
            field=models.CharField(default=' ', max_length=300),
        ),
        migrations.AlterField(
            model_name='usage_record',
            name='postedby_may',
            field=models.CharField(default=' ', max_length=300),
        ),
        migrations.AlterField(
            model_name='usage_record',
            name='postedby_nov',
            field=models.CharField(default=' ', max_length=300),
        ),
        migrations.AlterField(
            model_name='usage_record',
            name='postedby_oct',
            field=models.CharField(default=' ', max_length=300),
        ),
        migrations.AlterField(
            model_name='usage_record',
            name='postedby_sept',
            field=models.CharField(default=' ', max_length=300),
        ),
        migrations.AlterField(
            model_name='usage_record',
            name='txrefnum_oct',
            field=models.CharField(default=' ', max_length=300),
        ),
    ]
