# Generated by Django 3.1.3 on 2021-07-15 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0046_auto_20210714_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemuser',
            name='password',
            field=models.BinaryField(max_length=100),
        ),
    ]
