# Generated by Django 3.1.3 on 2021-07-15 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0047_auto_20210715_0804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemuser',
            name='password',
            field=models.CharField(max_length=100),
        ),
    ]
