# Generated by Django 3.1.3 on 2021-07-15 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0048_auto_20210715_0807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemuser',
            name='password',
            field=models.BinaryField(max_length=1000),
        ),
    ]
