# Generated by Django 3.1.3 on 2021-07-15 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0051_auto_20210715_0908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemuser',
            name='password',
            field=models.CharField(max_length=1000),
        ),
    ]
