# Generated by Django 3.1.3 on 2021-07-20 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0053_auto_20210715_0915'),
    ]

    operations = [
        migrations.AddField(
            model_name='revenuecode',
            name='fix_amount_flag',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='revenuecode',
            name='fix_amount_penalty',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='revenuecode',
            name='penalty_after',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='revenuecode',
            name='percentage_flag',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='revenuecode',
            name='percentage_penalty',
            field=models.FloatField(default=0),
        ),
    ]
