# Generated by Django 3.1.3 on 2021-07-21 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0054_auto_20210720_1315'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='revenuecode',
            name='fix_amount_flag',
        ),
        migrations.RemoveField(
            model_name='revenuecode',
            name='percentage_flag',
        ),
    ]
