# Generated by Django 3.1.3 on 2021-07-21 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0055_auto_20210721_1253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usage_record',
            name='penalty_flag',
        ),
        migrations.AddField(
            model_name='account_info',
            name='penalty_flag',
            field=models.IntegerField(default=-1),
        ),
    ]
