# Generated by Django 3.1.3 on 2021-07-21 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0056_auto_20210721_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='account_info',
            name='deleted_flag',
            field=models.CharField(default='0', max_length=30),
        ),
        migrations.AddField(
            model_name='consumers_info',
            name='deleted_flag',
            field=models.CharField(default='0', max_length=30),
        ),
    ]
