# Generated by Django 3.1.3 on 2021-07-21 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0057_auto_20210721_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumers_info',
            name='middlename',
            field=models.CharField(default='', max_length=30),
        ),
    ]
