# Generated by Django 3.1.3 on 2021-07-22 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0058_auto_20210721_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account_info',
            name='penalty_flag',
            field=models.IntegerField(default=0),
        ),
    ]
