# Generated by Django 3.1.3 on 2021-07-23 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0059_auto_20210722_0846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account_info',
            name='barangay',
            field=models.CharField(default='01', max_length=50),
        ),
        migrations.AlterField(
            model_name='account_info',
            name='deleted_flag',
            field=models.CharField(default='0', max_length=50),
        ),
        migrations.AlterField(
            model_name='applicants_info',
            name='applicantid',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='applicants_info',
            name='checker_comment',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='applicants_info',
            name='consumerid',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='applicants_info',
            name='date_checkerapproval',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='applicants_info',
            name='date_ingeneerapproval',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='applicants_info',
            name='date_mayorapproval',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='applicants_info',
            name='engineer_comment',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='applicants_info',
            name='mobilenumber',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='applicants_info',
            name='mobilenumber2',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='applicants_info',
            name='required_files',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='applicants_info',
            name='required_image',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='barangay_report',
            name='barangay_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='barangay_report',
            name='barangay_val',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='consumers_info',
            name='consumerid',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='consumers_info',
            name='deleted_flag',
            field=models.CharField(default='0', max_length=50),
        ),
        migrations.AlterField(
            model_name='consumers_info',
            name='mobilenumber',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='consumers_info',
            name='mobilenumber2',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='consumers_info',
            name='oldconsumerid',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='gettotalbill',
            name='bill_id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='gettotalbill',
            name='con_id',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='gettotalbill',
            name='paid',
            field=models.CharField(default=' ', max_length=50),
        ),
        migrations.AlterField(
            model_name='gettotalbill',
            name='rateid',
            field=models.CharField(default=' ', max_length=50),
        ),
        migrations.AlterField(
            model_name='gettotalbill',
            name='reading_date',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='meterreadingmodification',
            name='accountinfoid',
            field=models.CharField(default='', max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='meterreadingmodification',
            name='date',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='meterreadingmodification',
            name='meternumber',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='meterreadingmodification',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='meterreadingmodification',
            name='postedby',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='oldcosumerinfo',
            name='address',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='oldcosumerinfo',
            name='con_category',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='oldcosumerinfo',
            name='con_id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='oldcosumerinfo',
            name='firstname',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='oldcosumerinfo',
            name='lastname',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='oldcosumerinfo',
            name='meternumber',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='oldcosumerinfo',
            name='middlename',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='primarykey_basis',
            name='classification',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='revenuecode',
            name='id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='systemuser',
            name='approver_flag',
            field=models.CharField(default='0', max_length=50),
        ),
        migrations.AlterField(
            model_name='usage_record',
            name='accountinfoid',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='usage_record',
            name='amountpaid_str_apr',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='usage_record',
            name='amountpaid_str_aug',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='usage_record',
            name='amountpaid_str_dec',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='usage_record',
            name='amountpaid_str_feb',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='usage_record',
            name='amountpaid_str_jan',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='usage_record',
            name='amountpaid_str_jul',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='usage_record',
            name='amountpaid_str_jun',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='usage_record',
            name='amountpaid_str_mar',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='usage_record',
            name='amountpaid_str_may',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='usage_record',
            name='amountpaid_str_nov',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='usage_record',
            name='amountpaid_str_oct',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='usage_record',
            name='amountpaid_str_sept',
            field=models.CharField(default='', max_length=500),
        ),
    ]
