# Generated by Django 3.1.3 on 2021-07-23 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0060_auto_20210723_0941'),
    ]

    operations = [
        migrations.AddField(
            model_name='usage_record',
            name='amountpaidstr',
            field=models.TextField(default=''),
        ),
    ]
