# Generated by Django 3.1.3 on 2021-07-23 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0061_usage_record_amountpaidstr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usage_record',
            name='amountpaidstr',
            field=models.TextField(default=' '),
        ),
    ]
