# Generated by Django 3.1.3 on 2021-07-23 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0062_auto_20210723_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usage_record',
            name='amountpaidstr',
            field=models.TextField(),
        ),
    ]
