# Generated by Django 3.1.3 on 2021-07-23 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0063_auto_20210723_1531'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account_info',
            name='middlename',
        ),
        migrations.RemoveField(
            model_name='usage_record',
            name='amountpaidstr',
        ),
    ]
