# Generated by Django 3.1.3 on 2021-07-23 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0064_auto_20210723_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='account_info',
            name='middlename',
            field=models.CharField(default='', max_length=30),
        ),
    ]
