# Generated by Django 3.1.3 on 2021-07-23 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0065_account_info_middlename'),
    ]

    operations = [
        migrations.AddField(
            model_name='usage_record',
            name='amountpaid_history',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='usage_record',
            name='datepaid_history',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='usage_record',
            name='postedby_history',
            field=models.TextField(default=''),
        ),
    ]
