# Generated by Django 3.1.3 on 2021-07-27 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0066_auto_20210723_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='usage_record',
            name='or_number_history',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='account_info',
            name='accountinfoid',
            field=models.CharField(max_length=45, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='account_info',
            name='address',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='account_info',
            name='duedate',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='account_info',
            name='firstname',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='account_info',
            name='lastname',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='account_info',
            name='meternumber',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='account_info',
            name='middlename',
            field=models.CharField(default='', max_length=45),
        ),
        migrations.AlterField(
            model_name='account_info',
            name='rateid',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='account_info',
            name='status',
            field=models.CharField(default='1', max_length=45),
        ),
        migrations.AlterField(
            model_name='applicants_info',
            name='barangay_installation',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='applicants_info',
            name='barangay_residence',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='applicants_info',
            name='birthday',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='applicants_info',
            name='firstname',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='applicants_info',
            name='homeaddress',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='applicants_info',
            name='installcount',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='applicants_info',
            name='lastname',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='applicants_info',
            name='mayor_comment',
            field=models.CharField(max_length=450),
        ),
        migrations.AlterField(
            model_name='applicants_info',
            name='middlename',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='applicants_info',
            name='sitio',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='consumers_info',
            name='barangay',
            field=models.CharField(default='01', max_length=45),
        ),
        migrations.AlterField(
            model_name='consumers_info',
            name='birthday',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='consumers_info',
            name='firstname',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='consumers_info',
            name='homeaddress',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='consumers_info',
            name='lastname',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='consumers_info',
            name='middlename',
            field=models.CharField(default='', max_length=45),
        ),
        migrations.AlterField(
            model_name='consumers_info',
            name='sitio',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='rates',
            name='paymentchedday',
            field=models.CharField(default='', max_length=45),
        ),
        migrations.AlterField(
            model_name='rates',
            name='rateid',
            field=models.CharField(max_length=45, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='usage_record',
            name='accountid',
            field=models.CharField(max_length=45, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='usage_record',
            name='datepaid_apr',
            field=models.CharField(default=' ', max_length=450),
        ),
        migrations.AlterField(
            model_name='usage_record',
            name='datepaid_aug',
            field=models.CharField(default=' ', max_length=450),
        ),
        migrations.AlterField(
            model_name='usage_record',
            name='datepaid_dec',
            field=models.CharField(default=' ', max_length=450),
        ),
        migrations.AlterField(
            model_name='usage_record',
            name='datepaid_feb',
            field=models.CharField(default=' ', max_length=450),
        ),
        migrations.AlterField(
            model_name='usage_record',
            name='datepaid_jan',
            field=models.CharField(default=' ', max_length=450),
        ),
        migrations.AlterField(
            model_name='usage_record',
            name='datepaid_jul',
            field=models.CharField(default=' ', max_length=450),
        ),
        migrations.AlterField(
            model_name='usage_record',
            name='datepaid_jun',
            field=models.CharField(default=' ', max_length=450),
        ),
        migrations.AlterField(
            model_name='usage_record',
            name='datepaid_mar',
            field=models.CharField(default=' ', max_length=450),
        ),
        migrations.AlterField(
            model_name='usage_record',
            name='datepaid_may',
            field=models.CharField(default=' ', max_length=450),
        ),
        migrations.AlterField(
            model_name='usage_record',
            name='datepaid_nov',
            field=models.CharField(default=' ', max_length=450),
        ),
        migrations.AlterField(
            model_name='usage_record',
            name='datepaid_oct',
            field=models.CharField(default=' ', max_length=450),
        ),
        migrations.AlterField(
            model_name='usage_record',
            name='datepaid_sept',
            field=models.CharField(default=' ', max_length=450),
        ),
        migrations.AlterField(
            model_name='usage_record',
            name='dateposted_apr',
            field=models.CharField(default=' ', max_length=45),
        ),
        migrations.AlterField(
            model_name='usage_record',
            name='dateposted_aug',
            field=models.CharField(default=' ', max_length=45),
        ),
        migrations.AlterField(
            model_name='usage_record',
            name='dateposted_dec',
            field=models.CharField(default=' ', max_length=45),
        ),
        migrations.AlterField(
            model_name='usage_record',
            name='dateposted_feb',
            field=models.CharField(default=' ', max_length=45),
        ),
        migrations.AlterField(
            model_name='usage_record',
            name='dateposted_jan',
            field=models.CharField(default=' ', max_length=45),
        ),
        migrations.AlterField(
            model_name='usage_record',
            name='dateposted_jul',
            field=models.CharField(default=' ', max_length=45),
        ),
        migrations.AlterField(
            model_name='usage_record',
            name='dateposted_jun',
            field=models.CharField(default=' ', max_length=45),
        ),
        migrations.AlterField(
            model_name='usage_record',
            name='dateposted_mar',
            field=models.CharField(default=' ', max_length=450),
        ),
        migrations.AlterField(
            model_name='usage_record',
            name='dateposted_may',
            field=models.CharField(default=' ', max_length=45),
        ),
        migrations.AlterField(
            model_name='usage_record',
            name='dateposted_nov',
            field=models.CharField(default=' ', max_length=45),
        ),
        migrations.AlterField(
            model_name='usage_record',
            name='dateposted_oct',
            field=models.CharField(default=' ', max_length=45),
        ),
        migrations.AlterField(
            model_name='usage_record',
            name='dateposted_sept',
            field=models.CharField(default=' ', max_length=45),
        ),
        migrations.AlterField(
            model_name='usage_record',
            name='postedby_apr',
            field=models.CharField(default=' ', max_length=450),
        ),
        migrations.AlterField(
            model_name='usage_record',
            name='postedby_aug',
            field=models.CharField(default=' ', max_length=450),
        ),
        migrations.AlterField(
            model_name='usage_record',
            name='postedby_dec',
            field=models.CharField(default=' ', max_length=450),
        ),
        migrations.AlterField(
            model_name='usage_record',
            name='postedby_feb',
            field=models.CharField(default=' ', max_length=450),
        ),
        migrations.AlterField(
            model_name='usage_record',
            name='postedby_jan',
            field=models.CharField(default=' ', max_length=450),
        ),
        migrations.AlterField(
            model_name='usage_record',
            name='postedby_jul',
            field=models.CharField(default=' ', max_length=450),
        ),
        migrations.AlterField(
            model_name='usage_record',
            name='postedby_jun',
            field=models.CharField(default=' ', max_length=450),
        ),
        migrations.AlterField(
            model_name='usage_record',
            name='postedby_mar',
            field=models.CharField(default=' ', max_length=450),
        ),
        migrations.AlterField(
            model_name='usage_record',
            name='postedby_may',
            field=models.CharField(default=' ', max_length=450),
        ),
        migrations.AlterField(
            model_name='usage_record',
            name='postedby_nov',
            field=models.CharField(default=' ', max_length=450),
        ),
        migrations.AlterField(
            model_name='usage_record',
            name='postedby_oct',
            field=models.CharField(default=' ', max_length=450),
        ),
        migrations.AlterField(
            model_name='usage_record',
            name='postedby_sept',
            field=models.CharField(default=' ', max_length=450),
        ),
        migrations.AlterField(
            model_name='usage_record',
            name='rateid',
            field=models.CharField(default=' ', max_length=45),
        ),
        migrations.AlterField(
            model_name='usage_record',
            name='reading_date_apr',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='usage_record',
            name='reading_date_aug',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='usage_record',
            name='reading_date_dec',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='usage_record',
            name='reading_date_feb',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='usage_record',
            name='reading_date_jan',
            field=models.CharField(default=' ', max_length=45),
        ),
        migrations.AlterField(
            model_name='usage_record',
            name='reading_date_jul',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='usage_record',
            name='reading_date_jun',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='usage_record',
            name='reading_date_mar',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='usage_record',
            name='reading_date_may',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='usage_record',
            name='reading_date_nov',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='usage_record',
            name='reading_date_oct',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='usage_record',
            name='reading_date_sept',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='usage_record',
            name='reading_postby_apr',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='usage_record',
            name='reading_postby_aug',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='usage_record',
            name='reading_postby_dec',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='usage_record',
            name='reading_postby_feb',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='usage_record',
            name='reading_postby_jan',
            field=models.CharField(default=' ', max_length=45),
        ),
        migrations.AlterField(
            model_name='usage_record',
            name='reading_postby_jul',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='usage_record',
            name='reading_postby_jun',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='usage_record',
            name='reading_postby_mar',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='usage_record',
            name='reading_postby_may',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='usage_record',
            name='reading_postby_nov',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='usage_record',
            name='reading_postby_oct',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='usage_record',
            name='reading_postby_sept',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='usage_record',
            name='txrefnum_apr',
            field=models.CharField(default=' ', max_length=45),
        ),
        migrations.AlterField(
            model_name='usage_record',
            name='txrefnum_aug',
            field=models.CharField(default=' ', max_length=45),
        ),
        migrations.AlterField(
            model_name='usage_record',
            name='txrefnum_dec',
            field=models.CharField(default=' ', max_length=45),
        ),
        migrations.AlterField(
            model_name='usage_record',
            name='txrefnum_feb',
            field=models.CharField(default=' ', max_length=45),
        ),
        migrations.AlterField(
            model_name='usage_record',
            name='txrefnum_jan',
            field=models.CharField(default=' ', max_length=45),
        ),
        migrations.AlterField(
            model_name='usage_record',
            name='txrefnum_jul',
            field=models.CharField(default=' ', max_length=45),
        ),
        migrations.AlterField(
            model_name='usage_record',
            name='txrefnum_jun',
            field=models.CharField(default=' ', max_length=45),
        ),
        migrations.AlterField(
            model_name='usage_record',
            name='txrefnum_mar',
            field=models.CharField(default=' ', max_length=45),
        ),
        migrations.AlterField(
            model_name='usage_record',
            name='txrefnum_may',
            field=models.CharField(default=' ', max_length=45),
        ),
        migrations.AlterField(
            model_name='usage_record',
            name='txrefnum_nov',
            field=models.CharField(default=' ', max_length=45),
        ),
        migrations.AlterField(
            model_name='usage_record',
            name='txrefnum_oct',
            field=models.CharField(default=' ', max_length=450),
        ),
        migrations.AlterField(
            model_name='usage_record',
            name='txrefnum_sept',
            field=models.CharField(default=' ', max_length=45),
        ),
    ]
