# Generated by Django 3.1.3 on 2021-07-27 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0067_auto_20210727_0906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usage_record',
            name='datepaid_apr',
            field=models.TextField(default=' '),
        ),
        migrations.AlterField(
            model_name='usage_record',
            name='datepaid_aug',
            field=models.TextField(default=' '),
        ),
        migrations.AlterField(
            model_name='usage_record',
            name='datepaid_dec',
            field=models.TextField(default=' '),
        ),
        migrations.AlterField(
            model_name='usage_record',
            name='datepaid_feb',
            field=models.TextField(default=' '),
        ),
        migrations.AlterField(
            model_name='usage_record',
            name='datepaid_jan',
            field=models.TextField(default=' '),
        ),
        migrations.AlterField(
            model_name='usage_record',
            name='datepaid_jul',
            field=models.TextField(default=' '),
        ),
        migrations.AlterField(
            model_name='usage_record',
            name='datepaid_jun',
            field=models.TextField(default=' '),
        ),
        migrations.AlterField(
            model_name='usage_record',
            name='datepaid_mar',
            field=models.TextField(default=' '),
        ),
        migrations.AlterField(
            model_name='usage_record',
            name='datepaid_may',
            field=models.TextField(default=' '),
        ),
        migrations.AlterField(
            model_name='usage_record',
            name='datepaid_nov',
            field=models.TextField(default=' '),
        ),
        migrations.AlterField(
            model_name='usage_record',
            name='datepaid_oct',
            field=models.TextField(default=' '),
        ),
        migrations.AlterField(
            model_name='usage_record',
            name='datepaid_sept',
            field=models.TextField(default=' '),
        ),
        migrations.AlterField(
            model_name='usage_record',
            name='dateposted_mar',
            field=models.TextField(default=' '),
        ),
        migrations.AlterField(
            model_name='usage_record',
            name='postedby_jan',
            field=models.TextField(default=' '),
        ),
        migrations.AlterField(
            model_name='usage_record',
            name='txrefnum_oct',
            field=models.TextField(default=' '),
        ),
    ]
