# Generated by Django 3.1.3 on 2021-07-27 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0068_auto_20210727_0908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicants_info',
            name='checker_comment',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='applicants_info',
            name='date_checkercommented',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='applicants_info',
            name='date_engineercommented',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='applicants_info',
            name='date_mayorcommented',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='applicants_info',
            name='engineer_comment',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='applicants_info',
            name='mayor_comment',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='applicants_info',
            name='required_files',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='applicants_info',
            name='required_image',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='usage_record',
            name='amountpaid_str_apr',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='usage_record',
            name='amountpaid_str_aug',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='usage_record',
            name='amountpaid_str_dec',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='usage_record',
            name='amountpaid_str_feb',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='usage_record',
            name='amountpaid_str_jan',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='usage_record',
            name='amountpaid_str_jul',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='usage_record',
            name='amountpaid_str_jun',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='usage_record',
            name='amountpaid_str_mar',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='usage_record',
            name='amountpaid_str_may',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='usage_record',
            name='amountpaid_str_nov',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='usage_record',
            name='amountpaid_str_oct',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='usage_record',
            name='amountpaid_str_sept',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='usage_record',
            name='postedby_apr',
            field=models.TextField(default=' '),
        ),
        migrations.AlterField(
            model_name='usage_record',
            name='postedby_aug',
            field=models.TextField(default=' '),
        ),
        migrations.AlterField(
            model_name='usage_record',
            name='postedby_dec',
            field=models.TextField(default=' '),
        ),
        migrations.AlterField(
            model_name='usage_record',
            name='postedby_feb',
            field=models.TextField(default=' '),
        ),
        migrations.AlterField(
            model_name='usage_record',
            name='postedby_jul',
            field=models.TextField(default=' '),
        ),
        migrations.AlterField(
            model_name='usage_record',
            name='postedby_jun',
            field=models.TextField(default=' '),
        ),
        migrations.AlterField(
            model_name='usage_record',
            name='postedby_mar',
            field=models.TextField(default=' '),
        ),
        migrations.AlterField(
            model_name='usage_record',
            name='postedby_may',
            field=models.TextField(default=' '),
        ),
        migrations.AlterField(
            model_name='usage_record',
            name='postedby_nov',
            field=models.TextField(default=' '),
        ),
        migrations.AlterField(
            model_name='usage_record',
            name='postedby_oct',
            field=models.TextField(default=' '),
        ),
        migrations.AlterField(
            model_name='usage_record',
            name='postedby_sept',
            field=models.TextField(default=' '),
        ),
    ]
