# Generated by Django 3.1.3 on 2021-07-27 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0069_auto_20210727_0912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemuser',
            name='firstname',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='systemuser',
            name='lastname',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='systemuser',
            name='middlename',
            field=models.CharField(default='', max_length=45),
        ),
        migrations.AlterField(
            model_name='systemuser',
            name='mobilenumber',
            field=models.CharField(default='', max_length=45),
        ),
        migrations.AlterField(
            model_name='systemuser',
            name='password',
            field=models.BinaryField(max_length=450),
        ),
        migrations.AlterField(
            model_name='systemuser',
            name='userid',
            field=models.CharField(max_length=45, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='systemuser',
            name='usertype',
            field=models.CharField(max_length=45),
        ),
    ]
