# Generated by Django 3.1.3 on 2021-08-10 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0070_auto_20210727_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='meterreadingmodification',
            name='id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='meterreadingmodification',
            name='accountinfoid',
            field=models.CharField(default='', max_length=50),
        ),
    ]
