# Generated by Django 3.1.4 on 2021-08-10 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0071_auto_20210810_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meterreadingmodification',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
