# Generated by Django 3.1.3 on 2021-08-11 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0072_auto_20210810_0624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meterreadingmodification',
            name='id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
    ]
