# Generated by Django 3.1.3 on 2021-08-12 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0074_auto_20210812_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meterreadingmodification',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
