# Generated by Django 3.1.3 on 2021-08-12 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0075_auto_20210812_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='account_info',
            name='previous_reading',
            field=models.FloatField(default=0),
        ),
    ]
