# Generated by Django 3.1.3 on 2021-08-13 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0076_account_info_previous_reading'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account_info',
            name='previous_reading',
        ),
        migrations.AddField(
            model_name='usage_record',
            name='previous_reading',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='meterreadingmodification',
            name='id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
    ]
