# Generated by Django 3.1.3 on 2021-08-13 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0077_auto_20210813_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meterreadingmodification',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
