# Generated by Django 3.1.3 on 2021-08-19 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0078_auto_20210813_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meterreadingmodification',
            name='id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
    ]
