# Generated by Django 3.1.3 on 2021-08-19 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0079_auto_20210819_0940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meterreadingmodification',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
