# Generated by Django 3.1.3 on 2021-08-20 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0081_payment_history'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment_history',
            old_name='podted_by',
            new_name='postedby',
        ),
    ]
