# Generated by Django 3.1.3 on 2021-08-27 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0082_auto_20210820_1147'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usage_record',
            old_name='reading_postby_apr',
            new_name='reading_postedby_apr',
        ),
        migrations.RenameField(
            model_name='usage_record',
            old_name='reading_postby_aug',
            new_name='reading_postedby_aug',
        ),
        migrations.RenameField(
            model_name='usage_record',
            old_name='reading_postby_dec',
            new_name='reading_postedby_dec',
        ),
        migrations.RenameField(
            model_name='usage_record',
            old_name='reading_postby_feb',
            new_name='reading_postedby_feb',
        ),
        migrations.RenameField(
            model_name='usage_record',
            old_name='reading_postby_jan',
            new_name='reading_postedby_jan',
        ),
        migrations.RenameField(
            model_name='usage_record',
            old_name='reading_postby_jul',
            new_name='reading_postedby_jul',
        ),
        migrations.RenameField(
            model_name='usage_record',
            old_name='reading_postby_jun',
            new_name='reading_postedby_jun',
        ),
        migrations.RenameField(
            model_name='usage_record',
            old_name='reading_postby_mar',
            new_name='reading_postedby_mar',
        ),
        migrations.RenameField(
            model_name='usage_record',
            old_name='reading_postby_may',
            new_name='reading_postedby_may',
        ),
        migrations.RenameField(
            model_name='usage_record',
            old_name='reading_postby_nov',
            new_name='reading_postedby_nov',
        ),
        migrations.RenameField(
            model_name='usage_record',
            old_name='reading_postby_oct',
            new_name='reading_postedby_oct',
        ),
        migrations.RenameField(
            model_name='usage_record',
            old_name='reading_postby_sept',
            new_name='reading_postedby_sept',
        ),
    ]
