# Generated by Django 3.1.3 on 2021-09-21 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0083_auto_20210827_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumers_info',
            name='emailaddress',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='systemuser',
            name='emailaddress',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
