# Generated by Django 3.2.9 on 2022-01-06 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0085_auto_20211012_1106'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment_history',
            name='year',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='usage_record',
            name='year',
            field=models.BigIntegerField(default=2022),
        ),
    ]
