# Generated by Django 3.2.9 on 2022-01-06 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0086_auto_20220106_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment_history',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
