# Generated by Django 3.2.9 on 2022-02-14 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0089_meterreadingmodification_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='account_info',
            name='stop_meter_flag',
            field=models.IntegerField(default=1),
        ),
    ]
