# Generated by Django 3.2.9 on 2022-02-14 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0091_alter_account_info_stop_meter_flag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account_info',
            name='stop_meter_flag',
        ),
    ]
