# Generated by Django 3.2.9 on 2022-02-14 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0092_remove_account_info_stop_meter_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='account_info',
            name='stop_meter_flag',
            field=models.IntegerField(default=0),
        ),
    ]
